export const tributesContents = {
  tributes: {
    page: {
      eyebrow: "In living legacy",
      bigTitle: "Tributes",
      headingCount: "1,247",
      headingSuffix: "lives, and counting.",
      subheading: "Each one is someone Baba and Mama changed. Add yours.",
      cta: "Add your tribute",
      portrait: {
        src: "/images/portraits/together.jpg",
        alt: "Revd. Gabriel and Mrs. Margaret Lasehinde — Baba and Mama GOMAL",
        caption: "Baba & Mama GOMAL",
      },
      addYoursSlotLabel: "Tell us what they did for you",
      bottomCta: "Add your tribute",
    },
    all: [
      {
        id: "t1",
        text: "Baba found me sleeping in the corridor with my luggage because I had no place to stay. He took me home, gave me a room, and kept me in school for three years. I never asked him how he afforded it.",
        name: "Adebayo Olatunji",
        relation: "GOMAL, Class of 2007",
      },
      {
        id: "t2",
        text: "Mama stayed with me the night before my final paper. I was shaking. She didn't say anything. She just sat there until I fell asleep. I have never forgotten that.",
        name: "Chidinma Eze",
        relation: "GOMAL, Class of 2012",
      },
      {
        id: "t3",
        text: "We nearly separated in 2019. They didn't take sides. They kept asking us questions until we found our own answers. We celebrate eight years next March.",
        name: "Anonymous",
        relation: "A couple they counselled",
      },
      {
        id: "t4",
        text: "Baba's chair at the front pew will never be filled by anyone else. We have tried not to replace it.",
        name: "Rev. Seun Adeyemi",
        relation: "Church, Ogbomoso",
      },
      {
        id: "t5",
        text: "Mama called to check on my daughter every term for four years. Not once did she ask for anything in return. I kept waiting for the ask. It never came.",
        name: "Funmi Babatunde",
        relation: "Parent, GOMAL 2018",
      },
      {
        id: "t6",
        text: "Every Sunday, Baba shook my hand like it was the most important thing he had done all week. For me, it was.",
        name: "Tunde Afolabi",
        relation: "GOMAL, Class of 2003",
      },
      {
        id: "t7",
        text: "She told me I was going to be fine three weeks before my exams. I had failed twice before. She didn't qualify it. She just said it. I was.",
        name: "Ngozi Okonkwo",
        relation: "GOMAL, Class of 2015",
      },
      {
        id: "t8",
        text: "They prayed over us at our wedding. Twenty-two years later we remember what they said word for word. Some things you don't forget.",
        name: "Mr & Mrs Adeleke",
        relation: "Counselled, 2002",
      },
      {
        id: "t9",
        text: "Baba told me the truth about my character in a way nobody had ever dared to. And then he stayed to help me fix it. That is rare.",
        name: "Taiwo Adegoke",
        relation: "GOMAL, Class of 2010",
      },
      {
        id: "t10",
        text: "When my father died and I had nobody to turn to, Mama said: 'Come and stay.' I stayed three months. She never charged me and never made me feel like a burden.",
        name: "Blessing Nwachukwu",
        relation: "GOMAL, Class of 2008",
      },
      {
        id: "t11",
        text: "Twenty-five years is not a school term. It is a generation. And they gave it, without holding back.",
        name: "Dr. Remi Adesanya",
        relation: "GOMAL Governing Board",
      },
      {
        id: "t12",
        text: "I came to GOMAL broken. I left with direction. I owe Baba and Mama more than I can say.",
        name: "Emeka Obi",
        relation: "GOMAL, Class of 2014",
      },
    ],
    submitModal: {
      heading: "Add your tribute",
      subheading: "Tell us what Baba or Mama did for you.",
      anonymousLabel: "Submit anonymously",
      namePlaceholder: "Your name",
      relationPlaceholder: "Your connection (e.g. GOMAL 2008)",
      textPlaceholder: "Tell us what they did for you...",
      textMaxLength: 600,
      submitCta: "Submit tribute",
      cancelCta: "Cancel",
      closeLabel: "Close",
      success: {
        heading: "Thank you.",
        body: "Your tribute has been received and will appear on the wall after a brief review.",
        closeCta: "Close",
      },
    },
  },
} as const;
